version: '2'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    entrypoint: "npm start"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:4.1.6
    ports:
      - "27017:27017"